import assert from 'node:assert/strict';
const base = process.argv[2] || 'https://transly-studio.adikagung32.chatgpt.site';
const origin = 'https://darlayx1.github.io';
const headers = { Origin: origin, 'Content-Type': 'application/json' };
const preflight = await fetch(base + '/api/credentials', { method: 'OPTIONS', headers: { Origin: origin, 'Access-Control-Request-Method': 'POST', 'Access-Control-Request-Headers': 'content-type,authorization' } });
assert.equal(preflight.status, 204);
assert.equal(preflight.headers.get('access-control-allow-origin'), origin);
const key = 'test-only-invalid-pages-key-123456';
const saved = await fetch(base + '/api/credentials', { method: 'POST', headers, body: JSON.stringify({ generator: key, evaluator: key }) });
assert.equal(saved.status, 200);
assert.equal(saved.headers.get('access-control-allow-origin'), origin);
assert(!(saved.headers.get('set-cookie') || '').includes('transly_credentials='));
const data = await saved.json();
assert.equal(typeof data.sessionToken, 'string');
assert(!JSON.stringify(data).includes(key));
const status = await fetch(base + '/api/credentials', { headers: { Origin: origin, Authorization: `Bearer ${data.sessionToken}` } });
assert.equal(status.headers.get('access-control-allow-origin'), origin);
assert.deepEqual(await status.json(), { generator: true, evaluator: true, custom: true, server: false });
const forbidden = await fetch(base + '/api/credentials', { method: 'POST', headers: { ...headers, Origin: 'https://other.test' }, body: JSON.stringify({ generator: key, evaluator: key }) });
assert.equal(forbidden.status, 403);
assert.equal(forbidden.headers.get('access-control-allow-origin'), null);
console.log('PASS Pages preflight, encrypted memory-session transport, credential status, and origin isolation');
