'use client';
import { useEffect, useRef, useState } from 'react';
import { Check, Sparkles, X, BookOpen, RotateCcw, CircleHelp, ChevronDown } from 'lucide-react';
import type { Annotation, PracticeSession } from '@/lib/transly/schema';
import { categoryLabels, severityInfo, models } from '@/lib/transly/config';
import { Modal } from './ui';

function FeedbackCard({ annotation }: { annotation: Annotation }) {
  return <div className="feedback-content"><span className={`severity-pill ${annotation.severity}`}>{severityInfo[annotation.severity].label}</span><blockquote>{annotation.originalText}</blockquote><h4>Yang perlu diperhatikan</h4><p>{annotation.explanation}</p>{annotation.context && <><h4>Makna dalam konteks</h4><p>{annotation.context}</p></>}<h4>Saran perbaikan</h4><p>{annotation.suggestion}</p>{annotation.improvedText && <div className="improved-text"><Check size={16}/><span>{annotation.improvedText}</span></div>}</div>;
}
export function AnnotatedText({ text, annotations }: { text: string; annotations: Annotation[] }) {
  const [active, setActive] = useState<Annotation | null>(null); const [sheet, setSheet] = useState(false); const [position, setPosition] = useState({ top: 0, left: 0 });
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const clear = () => { if (timer.current) clearTimeout(timer.current); };
  const close = () => { clear(); setActive(null); setSheet(false); };
  useEffect(() => { const dismiss = () => { setActive(null); setSheet(false); }; const scroll = () => { if (!sheet) setActive(null); }; const key = (e: KeyboardEvent) => { if (e.key === 'Escape') dismiss(); }; window.addEventListener('resize', dismiss); window.addEventListener('scroll', scroll, true); window.addEventListener('keydown', key); return () => { clear(); window.removeEventListener('resize', dismiss); window.removeEventListener('scroll', scroll, true); window.removeEventListener('keydown', key); }; }, [sheet]);
  function show(a: Annotation, element: HTMLElement, clicked = false) {
    clear(); const touch = window.matchMedia('(max-width: 640px), (hover: none)').matches;
    if (touch && !clicked) return;
    if (touch) { setSheet(true); setActive(a); return; }
    const rect = element.getBoundingClientRect(); const cardHeight = Math.min(410, window.innerHeight - 32);
    setPosition({ left: Math.max(16, Math.min(rect.left, window.innerWidth - 376)), top: rect.bottom + cardHeight + 12 < window.innerHeight ? rect.bottom + 8 : Math.max(16, rect.top - cardHeight - 8) }); setSheet(false); setActive(a);
  }
  const pieces: React.ReactNode[] = []; let cursor = 0;
  [...annotations].sort((a, b) => a.start - b.start || b.end - a.end).forEach((a, i) => {
    if (a.start < cursor || a.end <= a.start || a.end > text.length || text.slice(a.start, a.end) !== a.originalText) return;
    pieces.push(text.slice(cursor, a.start));
    pieces.push(<button className={`annotation ${a.severity}`} key={`${i}-${a.start}`} aria-label={`${severityInfo[a.severity].label}: ${a.originalText}. Buka feedback.`} onMouseEnter={e => show(a, e.currentTarget)} onMouseLeave={() => { if (window.matchMedia('(max-width: 640px), (hover: none)').matches) return; timer.current = setTimeout(() => setActive(null), 200); }} onFocus={e => show(a, e.currentTarget)} onClick={e => show(a, e.currentTarget, true)}>{text.slice(a.start, a.end)}</button>); cursor = a.end;
  }); pieces.push(text.slice(cursor));
  return <><div className="annotated-text prose">{text ? pieces : <span className="muted">Tidak ada terjemahan yang dikirim.</span>}</div>{active && !sheet && <aside className="feedback-popover" role="dialog" aria-label="Feedback terjemahan" style={position} onMouseEnter={clear} onMouseLeave={() => { timer.current = setTimeout(close, 200); }}><button className="icon-button feedback-close" aria-label="Tutup feedback" onClick={close}><X size={17}/></button><FeedbackCard annotation={active}/></aside>}<Modal open={sheet && Boolean(active)} title="Feedback terjemahan" onClose={close} className="feedback-sheet">{active && <FeedbackCard annotation={active}/>}</Modal></>;
}
export function Review({ session, onNew }: { session: PracticeSession; onNew: () => void }) {
  const result = session.result!; const [tab, setTab] = useState<'user' | 'ideal'>('user'); const [filter, setFilter] = useState<string | null>(null);
  const visible = filter ? result.annotations.filter(a => a.severity === filter) : result.annotations;
  const scoreLabel = result.overallScore >= 90 ? 'Sangat baik' : result.overallScore >= 75 ? 'Langkah yang bagus' : result.overallScore >= 55 ? 'Terus berkembang' : 'Masih ada ruang belajar';
  return <main className="review-main"><div className="review-heading"><div><div className="eyebrow">SELESAI DITINJAU <span className="pill">{session.config.level}</span></div><h1>Setiap kata, sebuah kemajuan.</h1><p className="muted">{session.challenge.title} · {session.challenge.topic}</p></div><button className="secondary-button" onClick={onNew}><RotateCcw size={17}/>Latihan baru</button></div>
    <section className="score-panel"><div className="overall-score"><div className="score-circle" style={{ '--score': `${result.overallScore}%` } as React.CSSProperties}><div><strong>{result.overallScore}</strong><span>dari 100</span></div></div><div><span className="mini-eyebrow">NILAI KESELURUHAN</span><h2>{scoreLabel}</h2><span className="muted small">Makna · bahasa · konteks</span></div></div><div className="score-breakdown">{Object.entries(result.categoryScores).map(([key, score]) => <div key={key}><span>{categoryLabels[key]}</span><div className="score-track"><div style={{ width: `${score}%` }}/></div><b>{Math.round(score)}</b></div>)}</div></section>
    <section className="main-feedback"><div className="section-label"><Sparkles size={19}/><h2>Catatan untukmu</h2></div><p>{result.summaryFeedback}</p><div className="feedback-columns"><div><h3><Check size={16}/>Sudah baik</h3><ul>{result.strengths.length ? result.strengths.map((s, i) => <li key={i}>{s}</li>) : <li>Mulai dengan satu kalimat untuk membangun kebiasaan menerjemahkan.</li>}</ul></div><div><h3><CircleHelp size={16}/>Fokus berikutnya</h3><ul>{result.weaknesses.length ? result.weaknesses.map((s, i) => <li key={i}>{s}</li>) : <li>Pertahankan ketelitian dan coba tantangan yang lebih kompleks.</li>}</ul></div></div></section>
    <div className="review-text-heading"><h2>Lebih dekat dengan terjemahanmu</h2><p className="muted small">Arahkan kursor atau ketuk bagian berwarna untuk memahami feedback.</p></div><div className="review-grid"><section className="review-source"><div className="pane-head"><span><BookOpen size={17}/>Teks sumber</span><span className="language-tag">ENGLISH</span></div><div className="prose source-text">{result.sourceText}</div></section><section className="review-translation"><div className="review-tabs"><button className={tab === 'user' ? 'active' : ''} onClick={() => setTab('user')}>Terjemahanmu</button><button className={tab === 'ideal' ? 'active' : ''} onClick={() => setTab('ideal')}><Sparkles size={15}/>Versi ideal</button></div>{tab === 'user' ? <><div className="annotation-legend">{Object.entries(severityInfo).map(([key, v]) => { const count = result.annotations.filter(a => a.severity === key).length; return <button key={key} title={v.detail} className={`legend-item ${key} ${filter === key ? 'active' : ''}`} aria-pressed={filter === key} onClick={() => setFilter(filter === key ? null : key)}><span/>{v.label}<b>{count}</b></button>; })}</div><AnnotatedText text={result.userTranslation} annotations={visible}/>{result.annotationWarnings ? <p className="annotation-note">Beberapa penanda AI tidak dapat ditempatkan dengan pasti. Rujuk rangkuman feedback untuk konteks lengkap.</p> : null}{!result.annotations.length && <p className="annotation-note">Tidak ada bagian yang ditandai. Lihat catatan di atas untuk penilaian lengkap.</p>}</> : <><div className="ideal-note"><Sparkles size={17}/><p>Salah satu versi yang natural. Terjemahan lain yang mempertahankan makna juga dapat benar.</p></div><div className="prose ideal-text">{result.idealTranslation}</div></>}</section></div>
    <details className="rubric"><summary>Cara penilaian <ChevronDown size={16}/></summary><p>Ketepatan makna 35%, kelengkapan 20%, kealamian 15%, tata bahasa 10%, pilihan kata 10%, dan gaya bahasa 10%. Saran kealamian bukan kesalahan. Nilai adalah panduan belajar dari AI dan dapat berbeda antar model.</p><p>Evaluator: {models.find(m => m.id === session.config.evaluator)?.name}</p></details><div className="review-end"><span>Ambil satu perbaikan. Bawa ke latihan berikutnya.</span><button className="primary-button" onClick={onNew}><RotateCcw size={17}/>Buat latihan berikutnya</button></div>
  </main>;
}

