'use client';
import { BookOpen, Clock3, Languages, Sparkles, SlidersHorizontal, Check, Plus, Feather, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import { levels, levelInfo, lengths, topics, styles, models } from '@/lib/transly/config';
import type { PracticeConfig, PracticeSession } from '@/lib/transly/schema';
import { ModelSelect, type KeyStatus } from './settings';

export function Setup({ config, onConfig, onStart, onSettings, status, session, onResume }: { config: PracticeConfig; onConfig: (c: PracticeConfig) => void; onStart: () => void; onSettings: () => void; status: KeyStatus; session: PracticeSession | null; onResume: () => void }) {
  const [custom, setCustom] = useState(Boolean(config.topic && !topics.includes(config.topic)));
  const change = <K extends keyof PracticeConfig>(key: K, value: PracticeConfig[K]) => onConfig({ ...config, [key]: value });
  return <main className="setup-main">
    <div className="page-intro"><div><div className="eyebrow"><span className="eyebrow-line"/>ENGLISH → INDONESIAN</div><h1>Temukan makna.<br/><span>Latih terjemahanmu.</span></h1><p>Latihan yang mengikuti kemampuanmu.<br className="desktop-break"/> Feedback yang membantumu melangkah lebih jauh.</p></div><div className="intro-note"><Languages size={22}/><span>Lebih dari sekadar<br/><b>kata demi kata.</b></span></div></div>
    {session && <button className="resume-banner" onClick={onResume}><BookOpen size={20}/><span><b>{session.result ? 'Lihat evaluasi terakhir' : 'Lanjutkan latihanmu'}</b><small>{session.challenge.title} · {session.config.level}</small></span><span className="pill">{session.result ? `${session.result.overallScore}/100` : 'Draft tersimpan'}</span></button>}
    <div className="setup-grid"><section className="setup-panel"><div className="panel-title"><span className="step-number">01</span><div><h2>Rancang latihanmu</h2><p>Mulai dari tantangan yang tepat.</p></div></div>
      <fieldset className="level-field"><legend>Tingkat kemahiran <span>CEFR</span></legend><div className="level-options">{levels.map(level => <button key={level} type="button" aria-pressed={config.level === level} className={config.level === level ? 'selected' : ''} onClick={() => change('level', level)}>{level === 'NAT' ? 'Native' : level}</button>)}</div><div className="level-description"><b>{levelInfo[config.level].name}</b><span>{levelInfo[config.level].detail}</span></div></fieldset>
      <div className="two-col config-row"><fieldset><legend>Panjang teks</legend><div className="length-options">{Object.entries(lengths).map(([key, l]) => <button key={key} aria-pressed={config.length === key} className={config.length === key ? 'selected' : ''} onClick={() => change('length', key as PracticeConfig['length'])}><b>{l.label}</b><small>{l.range} kata</small></button>)}</div></fieldset><label className="field"><span><Clock3 size={16}/>Durasi latihan</span><select value={config.duration} onChange={e => change('duration', Number(e.target.value))}>{[5, 10, 15, 20, 30, 45, 60].map(n => <option value={n} key={n}>{n} menit</option>)}</select><small className="muted">Fokus menulis, satu sesi penuh.</small></label></div>
      <div className="two-col config-row"><label className="field"><span>Topik <em>Opsional</em></span><select value={custom ? 'custom' : config.topic} onChange={e => { setCustom(e.target.value === 'custom'); change('topic', e.target.value === 'custom' ? '' : e.target.value); }}><option value="">Pilihkan untuk saya</option>{topics.map(t => <option key={t}>{t}</option>)}<option value="custom">Topik sendiri…</option></select></label><label className="field"><span>Gaya bahasa <em>Opsional</em></span><select value={config.style} onChange={e => change('style', e.target.value)}><option value="">Sesuaikan otomatis</option>{styles.map(s => <option key={s}>{s}</option>)}</select></label></div>
      {custom && <label className="field custom-topic"><span>Topik pilihanmu</span><input placeholder="Misalnya: kehidupan di kota masa depan" maxLength={120} value={config.topic} onChange={e => change('topic', e.target.value)}/></label>}
      <div className="ai-strip"><div className="section-label"><Sparkles size={17}/><h3>Pasangan AI</h3><button className="text-button" onClick={onSettings}><SlidersHorizontal size={15}/>Key & pengaturan</button></div><div className="two-col"><ModelSelect role="generator" value={config.generator} onChange={v => change('generator', v)}/><ModelSelect role="evaluator" value={config.evaluator} onChange={v => change('evaluator', v)}/></div><div className={`key-status ${status.generator && status.evaluator ? 'connected' : ''}`}><ShieldCheck size={14}/>{status.generator && status.evaluator ? 'API key siap digunakan' : 'Tambahkan API key di pengaturan untuk mulai'}</div></div>
      <div className="setup-action"><span><Clock3 size={16}/>{config.duration} menit · {lengths[config.length].range} kata</span><button className="primary-button" onClick={onStart}><Sparkles size={18}/>Buat latihan</button></div>
    </section><aside className="learning-panel"><div className="mini-eyebrow">CARA KERJANYA</div><h2>Satu teks.<br/>Banyak hal baru.</h2><ol className="learning-steps"><li><span><BookOpen size={19}/></span><div><h3>Baca dengan saksama</h3><p>Kenali konteks dan maksud di balik setiap kalimat.</p></div></li><li><span><Feather size={19}/></span><div><h3>Tulis dengan caramu</h3><p>Terjemahkan secara mandiri. Pertahankan makna, temukan kata yang natural.</p></div></li><li><span><Sparkles size={19}/></span><div><h3>Pelajari feedback</h3><p>Pahami yang sudah tepat, perbaiki yang masih terlewat.</p></div></li></ol><div className="learning-insight"><span className="quote-mark">“</span><p>Terjemahan yang baik terasa seperti ditulis dalam bahasa tujuannya.</p><div className="small">MAKNA DULU, KATA KEMUDIAN.</div></div><div className="learning-footer"><Check size={16}/><span>Alternatif yang akurat tetap dihargai.</span></div></aside></div>
    <div className="setup-bottom"><span>Ruang belajar yang fokus. Kemajuan, satu latihan pada satu waktu.</span><span>Made for meaning.</span></div>
  </main>;
}
